### ISSUE TITLE
Segmentation fault with std::unique_ptr<log4cpp::Appender>

### ISSUE THREAD

**Issue by kasru** [orocos-toolchain/log4cpp#13] opened 2018-03-18 19:49 UTC
Segmentation fault in the end of program.
g++ (Debian 4.9.2-10) 4.9.2
```C++
#include <chrono>
#include <iostream>
#include <memory>

#include "log4cpp/Category.hh"
#include "log4cpp/Appender.hh"
#include "log4cpp/FileAppender.hh"
#include "log4cpp/Layout.hh"
#include "log4cpp/BasicLayout.hh"
#include "log4cpp/Priority.hh"


int main(int, char *[])
{
    using namespace std::chrono;
    using clock = steady_clock;

    int howmany = 1000000;

    std::unique_ptr<log4cpp::Appender> appender( new log4cpp::FileAppender("default", "logs/log4cpp-bench.log") );
    appender->setLayout(new log4cpp::BasicLayout());

    log4cpp::Category& root = log4cpp::Category::getRoot();
    root.addAppender(appender.get());
    root.setPriority(log4cpp::Priority::INFO);

    auto start = clock::now();
    for (int i = 0; i < howmany; ++i)
        root << log4cpp::Priority::INFO << "log4cpp message # " << i << ": This is some text for your pleasure";

    duration<float> delta = clock::now() - start;
    float deltaf = delta.count();
    auto rate = howmany / deltaf;

    std::cout << "Total: " << howmany << std::endl;
    std::cout << "Delta = " << deltaf << " seconds" << std::endl;
    std::cout << "Rate = " << rate << "/sec" << std::endl;

    root.shutdown();
    return 0;
}

```

**Comment by meyerj** [comment] 2019-04-16 11:37
This GitHub project is a fork of the upstream repository at SourceForge, https://sourceforge.net/projects/log4cpp/, to be used within the [Orocos](http://www.orocos.org) project. It adds cmake build support and some minor patches to enable logging in real-time, output thread IDs or more precise time stamps.

The reported segmentation fault is most likely not related to any of these changes. I think the issue is that if you call [log4cpp::Category::addAppender(Appender *)](https://github.com/orocos-toolchain/log4cpp/blob/683cbb7f3ae19c5f703a467e9cf77fc7c140c6db/src/Category.cpp#L103) with a bare pointer, the `Category` takes ownership of the instance and you are not allowed to delete it manually anymore, which is what happens when the `unique_ptr` goes out of scope. Try to replace the line by

```cpp
root.addAppender(appender.release());
// appender == nullptr from here.
```

If you still think there is an issue within [log4cpp](https://sourceforge.net/projects/log4cpp/), please reopen the issue or report a bug to the [upstream issue tracker](https://sourceforge.net/p/log4cpp/bugs/).

**Closed by meyerj** 2019-04-16 11:37 UTC
